In [0]:
import pandas as pd
import numpy as np
import os

In [0]:
DIRE = "C:/Users/ATOMS8/Data/"
FILN = os.listdir("C:/Users/ATOMS8/Data/")

In [0]:
cache_ = {}
null_sum = 0
for i in range(len(FILN)):
    if FILN[i].endswith('.csv'):
        DF = pd.read_csv(DIRE + FILN[i], encoding = "CP949")
        null_sum += DF.isnull().sum()
        print("step == {}".format(i))
        
print("================DONE================")
print(null_sum)

step == 4
step == 5
step == 6
step == 7
step == 8
step == 9
step == 10
step == 11
step == 12
step == 13
step == 14
step == 15
step == 16
step == 17
step == 18
step == 19
step == 20
step == 21
step == 22
step == 23
step == 24
step == 25
step == 26
step == 27
step == 28
step == 29
step == 30
step == 31
step == 32
step == 33
step == 34
step == 35
step == 36
step == 37
step == 38
step == 39
step == 40
step == 41
step == 42
step == 43
step == 44
step == 45
step == 46
step == 47
step == 48
step == 49
step == 50
step == 51
step == 52
step == 53
step == 54
step == 55
step == 56
step == 57
step == 58
step == 59
step == 60
step == 61
step == 62
step == 63
step == 64
step == 65
step == 66
step == 67
step == 68
step == 69
step == 70
step == 71
step == 72
step == 73
step == 74
step == 75
step == 76
step == 77
step == 78
step == 79
step == 80
step == 81
step == 82
step == 83
step == 84
step == 85
step == 86
step == 87
step == 88
step == 89
step == 90
step == 91
step == 92
step == 93
step == 94
step == 95
step == 96
step == 97
step == 98
step == 99
step == 100
step == 101
step == 102
step == 103
step == 104
step == 105
step == 106
step == 107
step == 108
step == 109
step == 110
step == 111
step == 112
step == 113
step == 114
step == 115
step == 116
step == 117
step == 118
step == 119
step == 120
step == 121
step == 122
step == 123
step == 124
step == 125
step == 126
step == 127
step == 128
step == 129
step == 130
step == 131
step == 132
step == 133
step == 134
step == 135
step == 136
step == 137
================DONE================
지점                0.0
시간                NaN
기온(°C)         1725.0
누적강수량(mm)     91605.0
풍향(deg)        8172.0
풍속(m/s)        8097.0
현지기압(hPa)      8015.0
해면기압(hPa)      7706.0
습도(%)           841.0
일사(MJ/m^2)    71355.0
일조(Sec)        1261.0
dtype: float64